[[stacks]]
name = "danny_downloads"
description = "Test stack for syncing"
tags = ["test"]
[stacks.config]
file_paths = "danny_downloads"
compose_file = "compose.yaml"
env_file = ".env"
server_id = "Bumblebee"
linked_repo = "damandan"
run_directory = "danny_downloads"
deploy = true
