services:
  bazarr-marlie:
    image: lscr.io/linuxserver/bazarr:latest
    container_name: bazarr-marlie
    environment:
      - PUID=1007
      - PGID=100
      - TZ=Etc/UTC
    stop_signal: SIGTERM  # or SIGINT
    stop_grace_period: 20s  # or other duration
    deploy:
      resources:
        limits:
          cpus: '0.5'
          memory: 256M
        reservations:
          memory: 128M
    volumes:
      - ${BAZARR_CONFIG_PATH}:/config
      - ${MOVIES_PATH}:/movies
    ports:
      - 20003:6767
    networks:
      - proxy
    restart: unless-stopped
    depends_on:
      - radarr-marlie
  radarr-marlie:
    image: ghcr.io/linuxserver/radarr
    container_name: radarr-marlie
    environment:
      - PUID=1004
      - PGID=100
      - TZ=Europe/Amsterdam
      - UMASK_SET=022
    stop_signal: SIGTERM  # or SIGINT
    stop_grace_period: 30s  # or other duration
    deploy:
      resources:
        limits:
          cpus: '0.5'
          memory: 256M
        reservations:
          memory: 128M
    volumes:
      - ${RADARR_CONFIG_PATH}:/config
      - ${MOVIES_PATH}:/movies
      - ${DOWNLOADS_PATH}:/downloads
    ports:
      - 20001:7878
    networks:
      - proxy
    restart: unless-stopped
    depends_on:
      - sabnzbd-marlie
  sabnzbd-marlie:
    image: ghcr.io/linuxserver/sabnzbd
    container_name: sabnzbd-marlie
    environment:
      - PUID=1006
      - PGID=100
      - TZ=Europe/Amsterdam
    stop_signal: SIGTERM  # or SIGINT
    stop_grace_period: 45s  # or other duration
    deploy:
      resources:
        limits:
         cpus: '0.5'
         memory: 1G
        reservations:
          memory: 256M
    volumes:
      - ${SABNZBD_CONFIG_PATH}:/config
      - ${DOWNLOADS_COMPLETED_PATH}:/config/Downloads/complete #optional
      - ${DOWNLOADS_INCOMPLETE_PATH}:/config/Downloads/incomplete #optional
    ports:
      - 20004:9090
    networks:
      - proxy
    restart: unless-stopped
networks:
  proxy:
    name: proxy
    external: true
