services:
  redis:
    image: redis:7
    container_name: paperless-redis
    restart: unless-stopped
    networks: [syno-proxy]
    volumes:
      - redisdata:/data
    deploy:
      resources:
        limits:
          memory: 256M
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 30s
      timeout: 5s
      retries: 5

  paperless:
    image: ghcr.io/paperless-ngx/paperless-ngx:latest
    container_name: paperless
    restart: unless-stopped
    depends_on:
      redis:
        condition: service_healthy
      db:
        condition: service_healthy
    networks: [syno-proxy, syno-mariadb]
    volumes:
      - paperless_data:/usr/src/paperless/data
      - paperless_media:/usr/src/paperless/media
      - ${PAPERLESS_EXPORT_PATH}:/usr/src/paperless/export
      - ${PAPERLESS_CONSUME_PATH}:/usr/src/paperless/consume
    environment:
      PAPERLESS_REDIS: redis://paperless-redis:6379
      PAPERLESS_DBHOST: mariadb
      PAPERLESS_DBPORT: 3306
      PAPERLESS_DBENGINE: mariadb
      PAPERLESS_DBNAME: ${PAPERLESS_DB_NAME}
      PAPERLESS_DBUSER: ${PAPERLESS_DB_USER}
      PAPERLESS_DBPASS: ${PAPERLESS_DB_PWD}
      PAPERLESS_URL: https://paperless.damandan.nl
      PAPERLESS_CSRF_TRUSTED_ORIGINS: https://paperless.damandan.nl
      PAPERLESS_TIME_ZONE: Europe/Amsterdam
      PAPERLESS_OCR_LANGUAGE: ${PAPERLESS_OCR_LANGUAGE}
      PAPERLESS_OCR_LANGUAGES: ${PAPERLESS_OCR_LANGUAGES}
      PAPERLESS_SECRET_KEY: ${PAPERLESS_SECRET_KEY}
      USER_ID: 1000
      GROUP_ID: 100
      PAPERLESS_GMAIL_OAUTH_CLIENT_ID: ${PAPERLESS_GMAIL_CLIENT}
      PAPERLESS_GMAIL_OAUTH_CLIENT_SECRET: ${PAPERLESS_GMAIL_SECRET}
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.paperless.rule=Host(`paperless.damandan.nl`)"
      - "traefik.http.routers.paperless.entrypoints=websecure"
      - "traefik.http.routers.paperless.tls=true"
      - "traefik.http.services.paperless.loadbalancer.server.port=8000"
      - "traefik.http.routers.paperless.middlewares=lan-and-tailscale@file"
    deploy:
      resources:
        limits:
          memory: 1.5G
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000"]
      interval: 30s
      timeout: 10s
      retries: 5

#  frigate:
#    image: ghcr.io/blakeblackshear/frigate:0.18.0
#    container_name: frigate
#    restart: always
#    privileged: true
#    shm_size: "1G"
#    networks: [syno-proxy]
#    ports:
#      - 8971:8971
#      - 5000:5000
#    devices:
#      - /dev/dri:/dev/dri
#      - ${USB_BUS_PATH}:/dev/bus/usb
#    device_cgroup_rules:
#      - 'c 189:* rmw'
#    volumes:
#      - ${LOCALTIME_PATH}:/etc/localtime:ro
#      - frigate_config:/config
#      - ${FRIGATE_MEDIA}:/media/frigate
#      - ${FRIGATE_MODEL_CACHE_PATH}:/config/model_cache
#      - ${FRIGATE_LABELMAP_COCO17}:/config/labelmap/labels-coco17.txt
#      - type: tmpfs
#        target: /tmp/cache
#        tmpfs:
#          size: 1000000000
#    labels:
#      - "traefik.enable=true"
#      - "traefik.http.routers.frigate.rule=Host(`frigate.damandan.nl`)"
#      - "traefik.http.routers.frigate.entrypoints=websecure"
#      - "traefik.http.routers.frigate.tls=true"
##      - "traefik.http.services.frigate.loadbalancer.server.scheme=https"
#      - "traefik.http.services.frigate.loadbalancer.server.port=8971"
#      - "traefik.http.routers.frigate.middlewares=lan-and-tailscale@file"
#    deploy:
#      resources:
#        limits:
#          memory: 1.5G
#    environment:
#      FRIGATE_MQTT_USER: ${FRIGATE_MQTT_USER}
#      FRIGATE_MQTT_PASSWORD: ${FRIGATE_MQTT_PASSWORD}
#      TZ: Europe/Amsterdam

  matter-server:
    image: ghcr.io/home-assistant-libs/python-matter-server:stable
    container_name: matter-server
    restart: always
    network_mode: host
    environment:
      PRODUCTION_MODE: true
    security_opt:
      - apparmor:unconfined
    volumes:
      - matter_data:/data/
      - ${DBUS_PATH}:/run/dbus:ro
    command: --log-level verbose --storage-path /data --paa-root-cert-dir /data/credentials --bluetooth-adapter 0 --primary-interface eth0
    stop_signal: SIGTERM
    stop_grace_period: 30s

  modbus-proxy:
    image: tiagocoutinho/modbus-proxy
    container_name: modbus-proxy
    restart: always
    ports:
      - "5020:1502"
    volumes:
      - ${MODBUS_PROXY_CONFIG_PATH}:/etc/modbus-proxy.yml
    stop_signal: SIGINT
    stop_grace_period: 20s
    deploy:
      resources:
        limits:
          memory: 128M

  db:
    image: mariadb:13.0.2
    container_name: mariadb
    restart: always
    environment:
      MARIADB_ROOT_PASSWORD: ${MARIADB_ROOT_PASSWORD}
      MARIADB_AUTO_UPGRADE: 1
    volumes:
      - mariadb_migration_data:/var/lib/mysql
      - ${MARIADB_CUSTOM_CNF_PATH}:/etc/mysql/conf.d/custom.cnf:ro
    ports:
      - "3306:3306"
    networks: [syno-mariadb]
    deploy:
      resources:
        limits:
          memory: 700M
    healthcheck:
      test: ["CMD-SHELL", "mariadb-admin ping -h 127.0.0.1 --silent"]
      interval: 10s
      timeout: 5s
      retries: 10
      start_period: 20s

  adminer:
    image: adminer
    container_name: adminer
    restart: no
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.adminer.rule=Host(`adminer.damandan.nl`)"
      - "traefik.http.routers.adminer.entrypoints=websecure"
      - "traefik.http.routers.adminer.tls=true"
      - "traefik.http.services.adminer.loadbalancer.server.port=8080"
      - "traefik.http.routers.adminer.middlewares=lan-and-tailscale@file"
    ports:
      - 8080:8080
    networks: [syno-proxy, syno-mariadb]

  spotweb:
    image: jgeusebroek/spotweb:dev
    container_name: spotweb
    depends_on:
      db:
        condition: service_healthy
    environment:
      TZ: Europe/Amsterdam
      SPOTWEB_DB_TYPE: pdo_mysql
      SPOTWEB_DB_HOST: ${SPOTWEB_DB_HOST}
      SPOTWEB_DB_PORT: ${SPOTWEB_DB_PORT}
      SPOTWEB_DB_NAME: ${SPOTWEB_DB_NAME}
      SPOTWEB_DB_USER: ${SPOTWEB_DB_USER}
      SPOTWEB_DB_PASS: ${SPOTWEB_DB_PASS}
      SPOTWEB_CRON_RETRIEVE: "*/15 * * * *"
      SPOTWEB_CRON_CACHE_CHECK: "10 */1 * * *"
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.spotweb.rule=Host(`www.damandan.nl`)"
      - "traefik.http.routers.spotweb.entrypoints=websecure"
      - "traefik.http.routers.spotweb.tls=true"
      - "traefik.http.services.spotweb.loadbalancer.server.port=80"
    networks: [syno-proxy, syno-mariadb]
    volumes:
      - spotweb_config:/config
    restart: always

  sonarr-danny:
    image: ghcr.io/linuxserver/sonarr
    container_name: sonarr-danny
    restart: always
    networks: [syno-proxy]
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.sonarr.rule=Host(`sonarr.damandan.nl`)"
      - "traefik.http.routers.sonarr.entrypoints=websecure"
      - "traefik.http.routers.sonarr.tls=true"
      - "traefik.http.services.sonarr.loadbalancer.server.port=8989"
      - "traefik.http.routers.sonarr.middlewares=lan-and-tailscale@file"
    depends_on:
      - sabnzbd
    environment:
      TZ: Europe/Amsterdam
      UMASK_SET: 022
    volumes:
      - sonarr_config:/config
      - ${DANNY_SERIES_PATH}:/tv
      - ${DANNY_DOWNLOADS_COMPLETED_PATH}:/downloads
    ports:
      - 8989:8989

  bazarr-danny:
    image: lscr.io/linuxserver/bazarr:latest
    container_name: bazarr-danny
    restart: always
    networks: [syno-proxy]
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.bazarr.rule=Host(`bazarr.damandan.nl`)"
      - "traefik.http.routers.bazarr.entrypoints=websecure"
      - "traefik.http.routers.bazarr.tls=true"
      - "traefik.http.services.bazarr.loadbalancer.server.port=6767"
      - "traefik.http.routers.bazarr.middlewares=lan-and-tailscale@file"
    depends_on:
      - radarr-danny
      - sonarr-danny
    environment:
      TZ: Europe/Amsterdam
    volumes:
      - bazarr_config:/config
      - ${DANNY_MOVIES_PATH}:/movies
      - ${DANNY_SERIES_PATH}:/tv
    ports:
      - 6767:6767

  radarr-danny:
    image: ghcr.io/linuxserver/radarr
    container_name: radarr-danny
    restart: always
    networks: [syno-proxy]
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.radarr.rule=Host(`radarr.damandan.nl`)"
      - "traefik.http.routers.radarr.entrypoints=websecure"
      - "traefik.http.routers.radarr.tls=true"
      - "traefik.http.services.radarr.loadbalancer.server.port=7878"
      - "traefik.http.routers.radarr.middlewares=lan-and-tailscale@file"
    depends_on:
      - sabnzbd
    environment:
      TZ: Europe/Amsterdam
      UMASK_SET: 022
    volumes:
      - radarr_config:/config
      - ${DANNY_MOVIES_PATH}:/movies
      - ${DANNY_DOWNLOADS_COMPLETED_PATH}:/downloads
    ports:
      - 7878:7878

  sabnzbd:
    image: ghcr.io/linuxserver/sabnzbd
    container_name: sabnzbd
    restart: always
    networks: [syno-proxy]
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.sabnzbd.rule=Host(`sabnzbd.damandan.nl`)"
      - "traefik.http.routers.sabnzbd.entrypoints=websecure"
      - "traefik.http.routers.sabnzbd.tls=true"
      - "traefik.http.services.sabnzbd.loadbalancer.server.port=8080"
      - "traefik.http.routers.sabnzbd.middlewares=lan-and-tailscale@file"
    environment:
      TZ: Europe/Amsterdam
    volumes:
      - sabnzbd_config:/config
      - ${DANNY_DOWNLOADS_COMPLETED_PATH}:/config/Downloads/complete
      - ${DANNY_DOWNLOADS_INCOMPLETE_PATH}:/config/Downloads/incomplete
    ports:
      - 9090:9090

  jellyfin:
    image: jellyfin/jellyfin:latest
    container_name: jellyfin
    ports:
      - 8096:8096
    networks: [syno-proxy]
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.jellyfin.rule=Host(`jellyfin.damandan.nl`)"
      - "traefik.http.routers.jellyfin.entrypoints=websecure"
      - "traefik.http.routers.jellyfin.tls=true"
      - "traefik.http.services.jellyfin.loadbalancer.server.port=8096"
      - "traefik.http.routers.jellyfin.middlewares=lan-and-tailscale@file"
    devices:
      - /dev/dri:/dev/dri
    volumes:
      - jellyfin_config:/config
      - jellyfin_cache:/cache
      - type: bind
        source: ${DANNY_SERIES_PATH}
        target: /tv
      - type: bind
        source: ${DANNY_MOVIES_PATH}
        target: /movies
        read_only: true
      - type: bind
        source: ${DANNY_MOVIES_2_PATH}
        target: /movies2
        read_only: true
    deploy:
      resources:
        limits:
          memory: 1.5G
    environment:
      JELLYFIN_PublishedServerUrl: https://jellyfin.damandan.nl
      TZ: Europe/Amsterdam
    restart: always

  mosquitto:
    image: eclipse-mosquitto:latest
    container_name: mosquitto
    restart: always
    networks: [syno-proxy]
    ports:
      - "1883:1883"
      - "9001:9001"
    volumes:
      - mosquitto_config:/mosquitto/config
      - mosquitto_data:/mosquitto/data
      - mosquitto_log:/mosquitto/log

networks:
  syno-proxy:
    name: syno-proxy
  syno-lan:
    driver: macvlan
    driver_opts:
      parent: enp5s0
      ipvlan_mode: l2
    ipam:
      config:
        - subnet: 192.168.2.0/24
          gateway: 192.168.2.1
  syno-mariadb:
    name: syno-mariadb
    driver: bridge

volumes:
  paperless_data:
  paperless_media:
  paperless_export:
  redisdata:
  frigate_config:
  frigate_media:
  homeassistant_config:
  matter_data:
  mariadb_data:
  mariadb_migration_data:
  spotweb_config:
  sonarr_config:
  bazarr_config:
  radarr_config:
  sabnzbd_config:
  jellyfin_config:
  jellyfin_cache:
  mosquitto_config:
  mosquitto_data:
  mosquitto_log:
  config:
    driver: local
  work:
    driver: local
  open-webui:
  data:
  media:
  pgdata:  