services:
  frigate:
    container_name: frigate
    privileged: true # this may not be necessary for all setups
    restart: unless-stopped
    image: ghcr.io/blakeblackshear/frigate:0.17.0-beta2
    shm_size: "1G" # update for your cameras based on calculation above
    devices:
      - ${USB_BUS_PATH}:/dev/bus/usb
    volumes:
      - ${LOCALTIME_PATH}:/etc/localtime:ro
      - ${FRIGATE_CONFIG_PATH}:/config
      - ${FRIGATE_MEDIA_PATH}:/media/frigate
      - type: tmpfs # Optional: 1GB of memory, reduces SSD/SD Card wear
        target: /tmp/cache
        tmpfs:
          size: 1000000000
    stop_signal: SIGINT  # or SIGINT
    stop_grace_period: 60s  # or other duration
    ports:
      - "10005:5000" # Internal unauthenticated access. Expose carefully.
      - "8554:8554" # RTSP feeds
      - "8555:8555/tcp" # WebRTC over tcp
      - "8555:8555/udp" # WebRTC over udp
      - "8971:8971"
      - "1984:1984"
    labels:
      - "com.centurylinklabs.watchtower.enable=true"
    networks:
      - proxy
    group_add:
      - "44"  # GID for video group
    device_cgroup_rules:
      - 'c 189:* rmw'
    environment:
      FRIGATE_MQTT_USER: ${FRIGATE_MQTT_USER}
      FRIGATE_MQTT_PASSWORD: ${FRIGATE_MQTT_PASSWORD}
      NVIDIA_VISIBLE_DEVICES: all
      NVIDIA_DRIVER_CAPABILITIES: all
    cap_add:
      - CAP_PERFMON
    deploy:
      resources:
        reservations:
          cpus: '4.0'
          memory: 3584M
          devices:
            - driver: nvidia
              count: 1
              capabilities: [gpu]
        limits:
          memory: 5G
networks:
  proxy:
    name: proxy
    external: true