services:
  traefik:
    image: traefik:v3.6.7
    container_name: traefik
    restart: always
    networks:
      - proxy
      - default
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ${DOCKER_SOCKET_PATH}:/var/run/docker.sock
      - ${TRAEFIK_STATIC_CONFIG_PATH}:/etc/traefik/traefik.yaml:ro
      - ${TRAEFIK_DYNAMIC_CONFIG_PATH}:/etc/traefik/dynamic.yaml:ro
#      - ${TRAEFIK_FULLCHAIN_PATH}:/letsencrypt/fullchain.pem
#      - ${TRAEFIK_PRIVKEY_PATH}:/letsencrypt/privkey.pem
      - ${TRAEFIK_ACME_PATH}:/letsencrypt/acme.json
      - ${TRAEFIK_TRANSIP_PATH}:/transip
    labels:
      # Enable self‑routing
      - "traefik.enable=true"
    environment:
      - TRANSIP_ACCOUNT_NAME=${TRANSIP_ACCOUNT_NAME}
      - TRANSIP_PRIVATE_KEY_PATH=${TRANSIP_PRIVATE_KEY_PATH}
    stop_signal: SIGTERM  # or SIGINT
    stop_grace_period: 30s  # or other duration
    deploy: 
      resources: 
        limits: 
          cpus: '0.5' 
          memory: 128M 
        reservations: 
          memory: 64M
  whoami:
    image: traefik/whoami
    container_name: whoami
    restart: unless-stopped
    networks:
      - proxy
      - default
networks:
  default:
    name: traefik
  proxy:
    name: proxy
