services:
  qbittorrent:
    image: lscr.io/linuxserver/qbittorrent:latest
    container_name: qbittorrent
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Etc/UTC
      - WEBUI_PORT=10008
      - TORRENTING_PORT=6881
    volumes:
      - ${QBITTORRENT_CONFIG_PATH}:/config
      - ${DOWNLOADS_PATH}:/downloads #optional
    ports:
      - 10008:10008
      - 6881:6881
      - 6881:6881/udp
    restart: unless-stopped
